/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ByIdItemRequestBuilderRequestsMetadata, type ByIdItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spool/byId
 */
export interface ByIdRequestBuilder extends BaseRequestBuilder<ByIdRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.spool.byId.item collection
     * @param id Unique identifier of the item
     * @returns {ByIdItemRequestBuilder}
     */
     byId(id: Guid) : ByIdItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByIdRequestBuilderUriTemplate = "{+baseurl}/api/spool/byId";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByIdRequestBuilderNavigationMetadata: Record<Exclude<keyof ByIdRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ByIdItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/* tslint:enable */
/* eslint-enable */
