/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSpoolBrandFromDiscriminatorValue, type SpoolBrand } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spoolbrand/all
 */
export interface AllRequestBuilder extends BaseRequestBuilder<AllRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SpoolBrand[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SpoolBrand[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AllRequestBuilderUriTemplate = "{+baseurl}/api/spoolbrand/all";
/**
 * Metadata for all the requests in the request builder.
 */
export const AllRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AllRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSpoolBrandFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
