/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SpoolRequestBuilderNavigationMetadata, type SpoolRequestBuilder } from './spool/index.js';
// @ts-ignore
import { SpoolbrandRequestBuilderNavigationMetadata, type SpoolbrandRequestBuilder } from './spoolbrand/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The spool property
     */
    get spool(): SpoolRequestBuilder;
    /**
     * The spoolbrand property
     */
    get spoolbrand(): SpoolbrandRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    spool: {
        navigationMetadata: SpoolRequestBuilderNavigationMetadata,
    },
    spoolbrand: {
        navigationMetadata: SpoolbrandRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
