/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithNameItemRequestBuilder, WithNameItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spool/byBrandName
 */
export interface ByBrandNameRequestBuilder extends BaseRequestBuilder<ByBrandNameRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.spool.byBrandName.item collection
     * @param name Unique identifier of the item
     * @returns {WithNameItemRequestBuilder}
     */
     byName(name: string) : WithNameItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByBrandNameRequestBuilderUriTemplate = "{+baseurl}/api/spool/byBrandName";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByBrandNameRequestBuilderNavigationMetadata: Record<Exclude<keyof ByBrandNameRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byName: {
        requestsMetadata: WithNameItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["name"],
    },
};
/* tslint:enable */
/* eslint-enable */
