/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithNameItemRequestBuilder, WithNameItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spoolbrand/byName
 */
export interface ByNameRequestBuilder extends BaseRequestBuilder<ByNameRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.spoolbrand.byName.item collection
     * @param name Unique identifier of the item
     * @returns {WithNameItemRequestBuilder}
     */
     byName(name: string) : WithNameItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByNameRequestBuilderUriTemplate = "{+baseurl}/api/spoolbrand/byName";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByNameRequestBuilderNavigationMetadata: Record<Exclude<keyof ByNameRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byName: {
        requestsMetadata: WithNameItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["name"],
    },
};
/* tslint:enable */
/* eslint-enable */
