/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateSpoolBrandModel}
 */
// @ts-ignore
export function createCreateSpoolBrandModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateSpoolBrandModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateSpoolModel}
 */
// @ts-ignore
export function createCreateSpoolModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateSpoolModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpoolBrand}
 */
// @ts-ignore
export function createSpoolBrandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpoolBrand;
}
export interface CreateSpoolBrandModel extends Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Spool}
 */
// @ts-ignore
export function createSpoolFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpool;
}
export interface CreateSpoolModel extends Parsable {
    /**
     * The brandId property
     */
    brandId?: Guid | null;
    /**
     * The color property
     */
    color?: string | null;
    /**
     * The material property
     */
    material?: string | null;
    /**
     * The weight property
     */
    weight?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateSpoolBrandModel}
 */
// @ts-ignore
export function createUpdateSpoolBrandModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateSpoolBrandModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateSpoolModel}
 */
// @ts-ignore
export function createUpdateSpoolModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateSpoolModel;
}
/**
 * The deserialization information for the current model
 * @param CreateSpoolBrandModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateSpoolBrandModel(createSpoolBrandModel: Partial<CreateSpoolBrandModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createSpoolBrandModel.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateSpoolModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateSpoolModel(createSpoolModel: Partial<CreateSpoolModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "brandId": n => { createSpoolModel.brandId = n.getGuidValue(); },
        "color": n => { createSpoolModel.color = n.getStringValue(); },
        "material": n => { createSpoolModel.material = n.getStringValue(); },
        "weight": n => { createSpoolModel.weight = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getNumberValue(); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Spool The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpool(spool: Partial<Spool> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "brand": n => { spool.brand = n.getObjectValue<SpoolBrand>(createSpoolBrandFromDiscriminatorValue); },
        "brandId": n => { spool.brandId = n.getGuidValue(); },
        "color": n => { spool.color = n.getStringValue(); },
        "id": n => { spool.id = n.getGuidValue(); },
        "material": n => { spool.material = n.getStringValue(); },
        "weight": n => { spool.weight = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SpoolBrand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpoolBrand(spoolBrand: Partial<SpoolBrand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { spoolBrand.id = n.getGuidValue(); },
        "name": n => { spoolBrand.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateSpoolBrandModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateSpoolBrandModel(updateSpoolBrandModel: Partial<UpdateSpoolBrandModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { updateSpoolBrandModel.id = n.getGuidValue(); },
        "name": n => { updateSpoolBrandModel.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateSpoolModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateSpoolModel(updateSpoolModel: Partial<UpdateSpoolModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "brandId": n => { updateSpoolModel.brandId = n.getGuidValue(); },
        "color": n => { updateSpoolModel.color = n.getStringValue(); },
        "id": n => { updateSpoolModel.id = n.getGuidValue(); },
        "material": n => { updateSpoolModel.material = n.getStringValue(); },
        "weight": n => { updateSpoolModel.weight = n.getNumberValue(); },
    }
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
/**
 * Serializes information the current object
 * @param CreateSpoolBrandModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateSpoolBrandModel(writer: SerializationWriter, createSpoolBrandModel: Partial<CreateSpoolBrandModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createSpoolBrandModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createSpoolBrandModel.name);
}
/**
 * Serializes information the current object
 * @param CreateSpoolModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateSpoolModel(writer: SerializationWriter, createSpoolModel: Partial<CreateSpoolModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createSpoolModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("brandId", createSpoolModel.brandId);
    writer.writeStringValue("color", createSpoolModel.color);
    writer.writeStringValue("material", createSpoolModel.material);
    writer.writeNumberValue("weight", createSpoolModel.weight);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!problemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", problemDetails.detail);
    writer.writeStringValue("instance", problemDetails.instance);
    writer.writeNumberValue("status", problemDetails.status);
    writer.writeStringValue("title", problemDetails.title);
    writer.writeStringValue("type", problemDetails.type);
    writer.writeAdditionalData(problemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Spool The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpool(writer: SerializationWriter, spool: Partial<Spool> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spool || isSerializingDerivedType) { return; }
    writer.writeObjectValue<SpoolBrand>("brand", spool.brand, serializeSpoolBrand);
    writer.writeGuidValue("brandId", spool.brandId);
    writer.writeStringValue("color", spool.color);
    writer.writeGuidValue("id", spool.id);
    writer.writeStringValue("material", spool.material);
    writer.writeNumberValue("weight", spool.weight);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpoolBrand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpoolBrand(writer: SerializationWriter, spoolBrand: Partial<SpoolBrand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spoolBrand || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", spoolBrand.id);
    writer.writeStringValue("name", spoolBrand.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateSpoolBrandModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateSpoolBrandModel(writer: SerializationWriter, updateSpoolBrandModel: Partial<UpdateSpoolBrandModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateSpoolBrandModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", updateSpoolBrandModel.id);
    writer.writeStringValue("name", updateSpoolBrandModel.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateSpoolModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateSpoolModel(writer: SerializationWriter, updateSpoolModel: Partial<UpdateSpoolModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateSpoolModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("brandId", updateSpoolModel.brandId);
    writer.writeStringValue("color", updateSpoolModel.color);
    writer.writeGuidValue("id", updateSpoolModel.id);
    writer.writeStringValue("material", updateSpoolModel.material);
    writer.writeNumberValue("weight", updateSpoolModel.weight);
}
export interface Spool extends Parsable {
    /**
     * The brand property
     */
    brand?: SpoolBrand | null;
    /**
     * The brandId property
     */
    brandId?: Guid | null;
    /**
     * The color property
     */
    color?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The material property
     */
    material?: string | null;
    /**
     * The weight property
     */
    weight?: number | null;
}
export interface SpoolBrand extends Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface UpdateSpoolBrandModel extends Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface UpdateSpoolModel extends Parsable {
    /**
     * The brandId property
     */
    brandId?: Guid | null;
    /**
     * The color property
     */
    color?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The material property
     */
    material?: string | null;
    /**
     * The weight property
     */
    weight?: number | null;
}
/* tslint:enable */
/* eslint-enable */
