/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllRequestBuilderRequestsMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { ByBrandNameRequestBuilderNavigationMetadata, type ByBrandNameRequestBuilder } from './byBrandName/index.js';
// @ts-ignore
import { ByColorRequestBuilderNavigationMetadata, type ByColorRequestBuilder } from './byColor/index.js';
// @ts-ignore
import { ByIdRequestBuilderNavigationMetadata, type ByIdRequestBuilder } from './byId/index.js';
// @ts-ignore
import { ByMaterialRequestBuilderNavigationMetadata, type ByMaterialRequestBuilder } from './byMaterial/index.js';
// @ts-ignore
import { CreateRequestBuilderRequestsMetadata, type CreateRequestBuilder } from './create/index.js';
// @ts-ignore
import { DeleteRequestBuilderRequestsMetadata, type DeleteRequestBuilder } from './delete/index.js';
// @ts-ignore
import { type UpdateRequestBuilder, UpdateRequestBuilderRequestsMetadata } from './update/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spool
 */
export interface SpoolRequestBuilder extends BaseRequestBuilder<SpoolRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The byBrandName property
     */
    get byBrandName(): ByBrandNameRequestBuilder;
    /**
     * The byColor property
     */
    get byColor(): ByColorRequestBuilder;
    /**
     * The byId property
     */
    get byId(): ByIdRequestBuilder;
    /**
     * The byMaterial property
     */
    get byMaterial(): ByMaterialRequestBuilder;
    /**
     * The create property
     */
    get create(): CreateRequestBuilder;
    /**
     * The deletePath property
     */
    get deletePath(): DeleteRequestBuilder;
    /**
     * The update property
     */
    get update(): UpdateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SpoolRequestBuilderUriTemplate = "{+baseurl}/api/spool";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SpoolRequestBuilderNavigationMetadata: Record<Exclude<keyof SpoolRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    all: {
        requestsMetadata: AllRequestBuilderRequestsMetadata,
    },
    byBrandName: {
        navigationMetadata: ByBrandNameRequestBuilderNavigationMetadata,
    },
    byColor: {
        navigationMetadata: ByColorRequestBuilderNavigationMetadata,
    },
    byId: {
        navigationMetadata: ByIdRequestBuilderNavigationMetadata,
    },
    byMaterial: {
        navigationMetadata: ByMaterialRequestBuilderNavigationMetadata,
    },
    create: {
        requestsMetadata: CreateRequestBuilderRequestsMetadata,
    },
    deletePath: {
        requestsMetadata: DeleteRequestBuilderRequestsMetadata,
    },
    update: {
        requestsMetadata: UpdateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
