/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllRequestBuilderRequestsMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { ByNameRequestBuilderNavigationMetadata, type ByNameRequestBuilder } from './byName/index.js';
// @ts-ignore
import { CreateRequestBuilderRequestsMetadata, type CreateRequestBuilder } from './create/index.js';
// @ts-ignore
import { DeleteRequestBuilderRequestsMetadata, type DeleteRequestBuilder } from './delete/index.js';
// @ts-ignore
import { type UpdateRequestBuilder, UpdateRequestBuilderRequestsMetadata } from './update/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spoolbrand
 */
export interface SpoolbrandRequestBuilder extends BaseRequestBuilder<SpoolbrandRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The byName property
     */
    get byName(): ByNameRequestBuilder;
    /**
     * The create property
     */
    get create(): CreateRequestBuilder;
    /**
     * The deletePath property
     */
    get deletePath(): DeleteRequestBuilder;
    /**
     * The update property
     */
    get update(): UpdateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SpoolbrandRequestBuilderUriTemplate = "{+baseurl}/api/spoolbrand";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SpoolbrandRequestBuilderNavigationMetadata: Record<Exclude<keyof SpoolbrandRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    all: {
        requestsMetadata: AllRequestBuilderRequestsMetadata,
    },
    byName: {
        navigationMetadata: ByNameRequestBuilderNavigationMetadata,
    },
    create: {
        requestsMetadata: CreateRequestBuilderRequestsMetadata,
    },
    deletePath: {
        requestsMetadata: DeleteRequestBuilderRequestsMetadata,
    },
    update: {
        requestsMetadata: UpdateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
