/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithMaterialItemRequestBuilder, WithMaterialItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spool/byMaterial
 */
export interface ByMaterialRequestBuilder extends BaseRequestBuilder<ByMaterialRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.spool.byMaterial.item collection
     * @param material Unique identifier of the item
     * @returns {WithMaterialItemRequestBuilder}
     */
     byMaterial(material: string) : WithMaterialItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByMaterialRequestBuilderUriTemplate = "{+baseurl}/api/spool/byMaterial";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByMaterialRequestBuilderNavigationMetadata: Record<Exclude<keyof ByMaterialRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byMaterial: {
        requestsMetadata: WithMaterialItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["material"],
    },
};
/* tslint:enable */
/* eslint-enable */
