/**
 * SpooltrackingAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateSpoolModel { 
    id?: string;
    brandId?: string | null;
    color?: string | null;
    material?: string | null;
    weight?: number | null;
}

