/**
 * SpooltrackingAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSpoolModel { 
    brandId?: string;
    color?: string | null;
    material?: string | null;
    weight?: number;
}

