/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithColorItemRequestBuilder, WithColorItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/spool/byColor
 */
export interface ByColorRequestBuilder extends BaseRequestBuilder<ByColorRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.spool.byColor.item collection
     * @param color Unique identifier of the item
     * @returns {WithColorItemRequestBuilder}
     */
     byColor(color: string) : WithColorItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByColorRequestBuilderUriTemplate = "{+baseurl}/api/spool/byColor";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByColorRequestBuilderNavigationMetadata: Record<Exclude<keyof ByColorRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byColor: {
        requestsMetadata: WithColorItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["color"],
    },
};
/* tslint:enable */
/* eslint-enable */
